### ISSUE TITLE
Scope of this project

### ISSUE THREAD

**Issue by birojnayak** [twsouthwick/systemweb-adapters-ui#2]
@twsouthwick really excited to see this... 
a) will this help porting an existing Webform (aspx (.NET Framework)) app to .NET Core as is or with small changes ?
b) Are there any OS dependencies ? Meaning it can work both in Windows/Linux ?

If both answers are yes, we would be happy to start digging and porting features...

**Comment by birojnayak** [comment]
closing... as I could run on Mac...

**Comment by twsouthwick** [comment]
Yes, the goal here is to try to get things running on .NET Core with minimal effort/changes to the code (including the aspx pages). Not sure of any dependencies (so far) on Windows. I'm explicitly not building on any of the hosting model in System.Web, but on ASP.NET Core.
