### ISSUE TITLE
Question / Advice

### ISSUE THREAD

**Issue by matthewblott** [twsouthwick/systemweb-adapters-ui#5]
This is a terrific initiative that I would definitely have used in the past. I actually ported a Web Forms application to Linux successfully a few years ago because I'd had too many pain points with Windows Server and the app wasn't worth rewriting (although there were some memory issues!). I wrote about it [here](https://blog.coderscoffeehouse.com/tech/2016-01-19-aspnet-linux-setup/). I thought I'd post a question as another legacy project I used was DotNetNuke which was the premier CMS in the .NET space at one time but they've been struggling with migrating for years because of platform constraints. Have you thought about reaching out to them to see if they'd sponsor the project? It might be worth asking.

**Comment by mitchelsellers** [comment]
@matthewblott I don't believe that this does anything to move the needle forward for us as it isn't a replacement to System.Web which is the fundamental limitation of moving a .NET Framework application to .NET Core.

**Comment by twsouthwick** [comment]
Thanks! I'm revisiting this and joined that thread you mentioned.
